### ISSUE TITLE
error to to push on heroku after added a css and image on static folder

### ISSUE THREAD

**Issue by abdoulmoumouni** [flatplanet/My-Address-Book#1]
git push heroku master
Counting objects: 75, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (72/72), done.
Writing objects: 100% (75/75), 600.26 KiB | 0 bytes/s, done.
Total 75 (delta 15), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> Installing requirements with pip
remote:
remote: -----> $ python manage.py collectstatic --noinput
remote:        /app/.heroku/python/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
remote:          """)
remote:        Traceback (most recent call last):
remote:          File "manage.py", line 15, in <module>
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
remote:            self.fetch_command(subcommand).run_from_argv(self.argv)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
remote:            self.execute(*args, **cmd_options)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
remote:            output = self.handle(*args, **options)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
remote:            collected = self.collect()
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 128, in collect
remote:            for original_path, processed_path, processed in processor:
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/whitenoise/storage.py", line 133, in post_process_with_compression
remote:            for name, hashed_name, processed in files:
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/whitenoise/storage.py", line 84, in post_process
remote:            for name, hashed_name, processed in files:
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 402, in post_process
remote:            yield from super().post_process(*args, **kwargs)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 236, in post_process
remote:            for name, hashed_name, processed, _ in self._post_process(paths, adjustable_paths, hashed_files):
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 293, in _post_process
remote:            content = pattern.sub(converter, content)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 194, in converter
remote:            force=True, hashed_files=hashed_files,
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 131, in _url
remote:            hashed_name = hashed_name_func(*args)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 342, in _stored_name
remote:            cache_name = self.clean_name(self.hashed_name(name))
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/whitenoise/storage.py", line 151, in hashed_name
remote:            name = super(CompressedManifestStaticFilesStorage, self).hashed_name(*args, **kwargs)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 91, in hashed_name
remote:            if not self.exists(filename):
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 308, in exists
remote:            return os.path.exists(self.path(name))
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 46, in path
remote:            return super().path(name)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 321, in path
remote:            return safe_join(self.location, name)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/_os.py", line 49, in safe_join
remote:            'component ({})'.format(final_path, base_path))
remote:        django.core.exceptions.SuspiciousFileOperation: The joined path (/tmp/assets/icons/font-awesome/fonts/fontawesome-webfont.eot) is located outside of the base path component (/tmp/build_1793fb5e35319a62d71932bae1fa9b03/staticfiles)
remote:
remote:  !     Error while running '$ python manage.py collectstatic --noinput'.
remote:        See traceback above for details.
remote:
remote:        You may need to update application code to resolve this error.
remote:        Or, you can disable collectstatic for this application:
remote:
remote:           $ heroku config:set DISABLE_COLLECTSTATIC=1
remote:
remote:        https://devcenter.heroku.com/articles/django-assets
remote:
remote: ****** Collectstatic environment variables:
remote:
remote:        PYTHONUNBUFFERED=1
remote:        DEFAULT_PYTHON_STACK=cedar-14
remote:        LD_LIBRARY_PATH=/app/.heroku/vendor/lib:/app/.heroku/python/lib:
remote:        RECOMMENDED_PYTHON_VERSION=python-3.6.6
remote:        BPLOG_PREFIX=buildpack.python
remote:        LANG=en_US.UTF-8
remote:        STACK=heroku-18
remote:        OLDPWD=/app/tmp/buildpacks/8790c95df255b386056ea169648fd4a33d1cb3fba81f73b536f26374f6af107145f64a5980db7a52177f63bb41527f360ebd2e3bef7b8917bda7b51cf284cfdb
remote:        C_INCLUDE_PATH=/app/.heroku/vendor/include:/app/.heroku/python/include:
remote:        WARNINGS_LOG=/tmp/tmp.Xp1SLZBGRN
remote:        SECRET_KEY=2lu(qwq&-@)(u8hasin*p_070$_36dso3(ovpd-r)rd+ki3zxv
remote:        CACHED_PYTHON_STACK=heroku-18
remote:        LATEST_37=python-3.7.0
remote:        LATEST_36=python-3.6.6
remote:        DYNO=run.6755
remote:        REQUEST_ID=1c3abec0-f6c6-b910-71c7-1ff7cf89ac66
remote:        SOURCE_VERSION=cbd3d628d29ff751d653d7526926690e09f91040
remote:        PWD=/tmp/build_1793fb5e35319a62d71932bae1fa9b03
remote:        HOME=/app
remote:        SQLITE3_VERSION=3.22.0-1
remote:        DATABASE_URL=postgres://macbmobfbzdtov:afb22e11b5c6a0dc8383cbfbfba6cce5f7f2c0f105ffdfb087f78ca8f18f29ec@ec2-54-83-27-165.compute-1.amazonaws.com:5432/dcrredk7l1l3os
remote:        PROFILE_PATH=/tmp/build_1793fb5e35319a62d71932bae1fa9b03/.profile.d/python.sh
remote:        DEBUG_COLLECTSTATIC=1
remote:        LIBRARY_PATH=/app/.heroku/vendor/lib:/app/.heroku/python/lib:
remote:        CACHE_DIR=/app/tmp/cache
remote:        LATEST_2=python-2.7.15
remote:        PIP_UPDATE=9.0.2
remote:        EXPORT_PATH=/app/tmp/buildpacks/8790c95df255b386056ea169648fd4a33d1cb3fba81f73b536f26374f6af107145f64a5980db7a52177f63bb41527f360ebd2e3bef7b8917bda7b51cf284cfdb/bin/../export
remote:        BIN_DIR=/app/tmp/buildpacks/8790c95df255b386056ea169648fd4a33d1cb3fba81f73b536f26374f6af107145f64a5980db7a52177f63bb41527f360ebd2e3bef7b8917bda7b51cf284cfdb/bin
remote:        SHLVL=3
remote:        PYTHONPATH=.
remote:        VENDOR_URL=https://lang-python.s3.amazonaws.com/heroku-18
remote:        CPLUS_INCLUDE_PATH=/app/.heroku/vendor/include:/app/.heroku/python/include:
remote:        BUILDPACK_LOG_FILE=/dev/fd/3
remote:        PATH=/app/.heroku/python/bin:/app/.heroku/vendor/bin::/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/tmp/codon/vendor/bin:/app/tmp/buildpacks/8790c95df255b386056ea169648fd4a33d1cb3fba81f73b536f26374f6af107145f64a5980db7a52177f63bb41527f360ebd2e3bef7b8917bda7b51cf284cfdb/vendor/:/app/tmp/buildpacks/8790c95df255b386056ea169648fd4a33d1cb3fba81f73b536f26374f6af107145f64a5980db7a52177f63bb41527f360ebd2e3bef7b8917bda7b51cf284cfdb/vendor/pip-pop
remote:        ENV_DIR=/tmp/d20180926-74-ol8bte
remote:        BUILD_DIR=/tmp/build_1793fb5e35319a62d71932bae1fa9b03
remote:        DEFAULT_PYTHON_VERSION=python-3.6.6
remote:        PKG_CONFIG_PATH=/app/.heroku/vendor/lib/pkgconfig:/app/.heroku/vendor/lib/pkg-config:/app/.heroku/python/lib/pkg-config:
remote:        _=/usr/bin/env
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to evening-fjord-73313.
remote:
To https://git.heroku.com/evening-fjord-73313.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/evening-fjord-73313.git'

**Comment by flatplanet** [comment]
The error message is telling you to try this command in the terminal:

*heroku config:set DISABLE_COLLECTSTATIC=1*

Give that a try...then save to git and try to push again.

**Comment by abdoulmoumouni** [comment]
thank you very much for your answer I have already done by visiting the tutorial on heroku and it has walked thank you once again
